### ISSUE TITLE
Add the direct calling security

### ISSUE THREAD

**Issue by geek92sunny** [expresstechsoftware/product-questions-answers-for-woocommerce#11]
> Create a PR

Need to add this check on every PHP files which is called by the WP: https://stackoverflow.com/questions/43212340/what-is-meant-by-if-defined-abspath 
Read why it is important.

**Comment by ruchitamalviya** [comment]
done

**Comment by geek92sunny** [comment]
> done

I do not see any new PR (pull request)?
