### ISSUE TITLE
Check Plugin with last 3 WordPress and last 2 WC versions

### ISSUE THREAD

**Issue by geek92sunny** [expresstechsoftware/product-questions-answers-for-woocommerce#19]
![image](https://github.com/expresstechsoftware/product-questions-answers-for-woocommerce/assets/25177811/4113f41d-9ffb-4140-bcfe-c9e46ec7243c)

- You can change versions easily with WP CLI: https://developer.wordpress.org/cli/commands/core/update/
- WooCommerce latest version is  8.0.2. The plugin has been tested only up to 6.7.0:

![image](https://github.com/expresstechsoftware/product-questions-answers-for-woocommerce/assets/25177811/580d616e-a692-4a3f-b754-522b0e97aa6c)

**Comment by ruchitamalviya** [comment]
compatiable with all WC and WP version.

**Comment by geek92sunny** [comment]
Update compatibility versions:
1. Plugin main file: change the version `Tested up to: 6.3`  , change `version: 1.2.3`
2. Readme.txt: change the version `Tested up to: 6.3`  .

Change the plugin version:
1. Plugin main file: change the version no to 1.2.3
2. languages/ets_q_n_a.pot: change the version no. to 1.2.3

push to the branch 'v1.2.3'

**Comment by ruchitamalviya** [comment]
plugin have only mention WC tested version

**Comment by ruchitamalviya** [comment]
changes done and pushed in repo v1.2.3

**Comment by geek92sunny** [comment]
> plugin have only mention WC tested version

![image](https://github.com/expresstechsoftware/product-questions-answers-for-woocommerce/assets/25177811/ba6fbd73-b5d5-4804-bfd7-3c971ab15110)

It has version number.

AND yes, updated the `WC tested up to` latestest WooCommerce version.

**Comment by ruchitamalviya** [comment]
yes i change everything and push previously
