### ISSUE TITLE
Inbuilt hooks

### ISSUE THREAD

**Issue by geek92sunny** [expresstechsoftware/product-questions-answers-for-woocommerce#4]
There are hooks this plugin inside the branch 'inbuilt-hooks', fetch hooks from that branch and add them in the new corresponding positions of the code in the followup commits.

**Comment by geek92sunny** [comment]
You have not added the filter for the login URL:  
`<a href="<?php echo $site_url.'/wp-login.php' ?>" class="ets-load-more">`

And, had you checked all the mails for new answers, for changes in the answers and all others available?

**Comment by ruchitamalviya** [comment]
not checked mail for new answer i will check now and update  soon.

**Comment by geek92sunny** [comment]
1. Add a new action, which will run when the question is submitted on the frontend, it will receive the submitted question as the data.
2. Add a new action which will run when question answers are updated at the backend, it will receive the complete data of QA array as the data.
