### ISSUE TITLE
Approval checkbox on admin QA listing

### ISSUE THREAD

**Issue by geek92sunny** [expresstechsoftware/product-questions-answers-for-woocommerce#5]
> Create a pull request

1. For the existing QA pairs, they are internally approved and appearing on the frontend, BUT their **Approve** checkbox should also be checked initially, so when saving it will be saved as approved as well.
I installed the latest plugin, initially all Q's were approved, a new Q was posted, it came as unapproved, I approved this Q and saved it, OBVIOUSLY, all other Q's became unapproved, it should have been noticed by you.
2. Notice the design of checkboxes in Firefox, it should also have been notice by you.

![image](https://user-images.githubusercontent.com/25177811/181012450-f44e0aad-af5e-4d53-ac39-18151a995a16.png)

**Comment by geek92sunny** [comment]
Check the 2nd point on all major browsers, Safari, Chrome, Firefox, Edge, Opera using Lambatest.

**Comment by ruchitamalviya** [comment]
checking all major browser using lambda test  not found any issue as well as check Windows  and Ubuntu both OS.

**Comment by ruchitamalviya** [comment]
both issues done
